builtin:
  - 'backend/builtin/**/*'
  - '!backend/builtin/**/spec/*'
external:
  - 'backend/external/**/*'
  - '!backend/external/**/spec/*'
internal:
  - 'backend/internal/**/*'
  - '!backend/internal/**/spec/*'
positioning:
  - "backend/positioning/**/*"
  - '!backend/positioning/**/spec/*'
speed:
  - "backend/speed/**/*"
proto:
  - "proto/**/*"
frontend:
  - 'frontend/**/*'
ci-cd:
  - '.github/**/*'
  - 'manifests/**/*'
  - '!manifests/**/deployment.yaml'
documentation:
  - '**/docs/**/*'
  - "**.md"
