builtin:
  - any:
    - 'backend/builtin/**/*'
    - '!backend/builtin/**/spec/*'
external:
  - any:
    - 'backend/external/**/*'
    - '!backend/external/**/spec/*'
internal:
  - any:
    - 'backend/internal/**/*'
    - '!backend/internal/**/spec/*'
positioning:
  - any:
    - "backend/positioning/**/*"
    - '!backend/positioning/**/spec/*'
speed:
  - "backend/speed/**/*"
protocolBuffer:
  - "proto/**/*"
frontend:
  - 'frontend/**/*'
ci-cd:
  - any:
    - '.github/**/*'
    - 'manifests/**/*'
    - '!manifests/**/deployment.yaml'
documentation:
  - any:
    - '**/docs/**/*'
    - "**.md"
