apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: traefik
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "*.gotti.dev"
    # This assumes tls-secret exists and the SSL
    # certificate contains a CN for foo.bar.com
    secretName: cloudflare-cert
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
