apiVersion: apps/v1
kind: Deployment
metadata:
  name: plarail2021-positioning
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: plarail2021-positioning
  template:
    metadata:
      labels:
        app: plarail2021-positioning
    spec:
      containers:
        - name: plarail2021-positioning
          image: ghcr.io/ueckoken/plarail2021-soft-receiver-test:d18a164-1637285004 # {"$imagepolicy": "plarail2021:webrtc-receiver"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
