apiVersion: v1
kind: Endpoints
metadata:
  name: test
  namespace: monitoring
  labels:
    app: plarail2021-test
subsets:
- addresses:
  - ip: 10.56.14.94
  ports:
  - name: web
    port: 80
    protocol: TCP
