apiVersion: v1
kind: Endpoints
metadata:
  name: test
  namespace: monitoring
  labels:
    app: plarail2021-test
subsets:
- addresses:
  - ip: 164.70.126.185
  ports:
  - name: prom
    port: 9100
    protocol: TCP
