apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: monitoring
  labels:
    app: plarail2021-test
spec:
  externalName: 130.153.17.100
  ports:
  - name: prom
    port: 80
    protocol: TCP
    targetPort: 80
  type: ExternalName
