apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: monitoring
  labels:
    app: plarail2021-test
spec:
  externalName: 164.70.126.185
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 9100
  type: ExternalName
