apiVersion: apps/v1
kind: Deployment
metadata:
  name: plarail2021-soft-backend-external
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: plarail2021-soft-backend-external
  template:
    metadata:
      labels:
        app: plarail2021-soft-backend-external
    spec:
      containers:
        - name: plarail2021-soft-backend-external
          image: ghcr.io/ueckoken/plarail2021-soft-external:e787b6c-1636175343 # {"$imagepolicy": "plarail2021:external"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: external-env
