apiVersion: v1
kind: Endpoints
metadata:
  name: speed
  namespace: monitoring
  labels:
    app: speed
subsets:
- addresses:
  - ip: 130.153.17.100
  ports:
  - name: prom
    port: 8081
    protocol: TCP
