apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: speed
  namespace: plarail2021
  labels:
    release: monitoring-prometheus
spec:
  selector:
    matchLabels:
      app: speed
  endpoints:
    - port: prom
      path: /metrics
