apiVersion: v1
kind: Service
metadata:
  name: speed
  namespace: monitoring
  labels:
    app: speed
spec:
  externalName: 130.153.17.100
  ports:
  - name: prom
    port: 80
    protocol: TCP
    targetPort: 8081
  type: ExternalName
