apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tlscert
  namespace: traefik
spec:
  secretName: cloudflare-cert
  dnsNames:
    - "external-plarail-chofufes2021.gotti.dev"
    - "plarail-chofufes2021.gotti.dev"
    - "webrtc-plarail-chofufes2021.gotti.dev"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
