apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: webrtc-sender
  namespace: plarail2021
spec:
  image: ghcr.io/ueckoken/plarail2021-soft-webrtc-sender
  interval: 1m0s
