apiVersion: apps/v1
kind: Deployment
metadata:
  name: plarail2021-soft-python
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: plarail2021-soft-python
  template:
    metadata:
      labels:
        app: plarail2021-soft-python
    spec:
      containers:
        - name: plarail2021-soft-python
          image: ghcr.io/ueckoken/plarail2021-soft-frontend-python:d18a164-1637285007 # {"$imagepolicy": "plarail2021:frontend-python"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: videocast
