apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  values:
    installCRDs: true
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: ">=1.5.4 <1.5.5"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 10m
