name: Deploy external

defaults:
  run:
    working-directory: ./backend/external

on:
  push:
    branches: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Go binary
        run: |-
          make build

      - name: set tag
        run: |-
          export TIMESTUMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTUMP" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./backend/external
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ueckoken/plarail2021-soft-external:${{ IMAGE_TAG }}
