name: WebRTC test

defaults:
  run:
    working-directory: ./frontend

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set tag
        run: |-
          export TIMESTUMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTUMP" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ghcr.io/ueckoken/plarail2021-soft-frontend:${{ env.IMAGE_TAG }}
