apiVersion: apps/v1
kind: Deployment
metadata:
  name: plarail2021-webrtc-receiver
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: plarail2021-webrtc-receiver
  template:
    metadata:
      labels:
        app: plarail2021-webrtc-receiver
    spec:
      containers:
        - name: plarail2021-webrtc-receiver
          image: ghcr.io/ueckoken/plarail2021-soft-receiver-test:f77bf6c-1637250142 # {"$imagepolicy": "plarail2021:webrtc-receiver"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: videocast
